/* eslint-disable @next/next/no-css-tags */
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Navbar from './../components/navbar';


export default function MyApp({ Component, pageProps }: AppProps) {
  return <div className='root-app'>
    <Head>
        <title>Vmax</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="stylesheet" href="/styles/globals" />
      </Head><Navbar />
    <Component {...pageProps} />  
  </div>
}
