import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
const Home: NextPage = () => {

  return (
    <> 
      <Head>
        <title>Vmax</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.container}>
        <Navbar />
        <main className={styles.main}>

          <h1 className={styles.title}>
            Hallo I am Vmax <a href="/favicon.ico" target="_blank" title="Create">Martis</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.tsx</code>
          </p>
        </main>

      </div>
      <Footer />
    </>

  )
}

export default Home
